# Generated by Django 4.1.2 on 2022-11-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_name", models.CharField(max_length=100)),
                ("p_rating", models.DecimalField(decimal_places=1, max_digits=5)),
                ("p_description", models.CharField(max_length=200)),
                ("p_buycount", models.IntegerField()),
                ("p_brand", models.CharField(max_length=100)),
                ("p_category", models.CharField(max_length=100)),
                ("p_image", models.ImageField(upload_to="cosx_home/images/")),
            ],
        ),
    ]
