# Generated by Django 4.1.2 on 2023-06-25 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosx_home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 25, 8, 11, 2, 776349, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
