# Generated by Django 4.1.2 on 2022-11-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosx_home", "0002_alter_products_p_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="p_price",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
            preserve_default=False,
        ),
    ]
