# Generated by Django 4.1.2 on 2022-11-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosx_home", "0004_alter_products_p_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="p_price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
