# Generated by Django 4.1.2 on 2022-11-14 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosx_home", "0006_wishlist_wallet_orders_cart"),
    ]

    operations = [
        migrations.RemoveField(model_name="orders", name="addr2",),
        migrations.RemoveField(model_name="orders", name="pincode",),
        migrations.AddField(
            model_name="orders",
            name="fname",
            field=models.CharField(default="John", max_length=100),
        ),
        migrations.AddField(
            model_name="orders",
            name="lname",
            field=models.CharField(default="Doe", max_length=100),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 14, 18, 11, 59, 352148, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
