# Generated by Django 4.1.2 on 2022-11-14 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosx_home", "0007_remove_orders_addr2_remove_orders_pincode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 14, 18, 13, 17, 645679, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="wallet",
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=7),
        ),
    ]
