# Generated by Django 4.1.2 on 2022-11-14 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosx_home", "0008_alter_orders_order_date_alter_wallet_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="email",
            field=models.EmailField(default="johndoe@email.com", max_length=50),
        ),
        migrations.AddField(
            model_name="orders",
            name="phoneNum",
            field=models.CharField(default="+911234567890", max_length=15),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 14, 18, 55, 52, 617978, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
