# Generated by Django 4.1.2 on 2022-11-15 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosx_home", "0010_alter_orders_order_date_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 15, 0, 1, 26, 340041, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
